### ISSUE TITLE
Working status?

### ISSUE THREAD

**Issue by Meverhart** [tytondon1234/Spero#1]
Is Spero currently in working condition?  Do you plan to migrate it to Laravel 5.3?

**Comment by tytondon1234** [comment]
Hey Meverhart,

It is. It would be extremely easy to port to Laravel 5.3. The documentation isn't exactly informative on how to use it. The main file is riotApi.php in the Public repository. In there you will want to specify the summoner name, server, champion name, etc. Then, wherever you want to use the information from the API, you will require the riotApi.php file into it. As simple as that. Then all the variables will be there for you to work with. If you are porting to Laravel 5.3. Just create a new Laravel project and pull down the riotApi.php file and put it into the Public repository of your newly created Laravel project. Then, require that file into your welcome and or home file and declare the summoner, server, champion, or item of your choosing in the riotApi.php file. It is still in development, technically speaking, but has come a long way. Let me know if you need help with anything or pointers. :)

Thanks,
Justin "TytonDon" Werner
